# Generated by Django 2.2.16 on 2023-04-29 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230429_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество ингредиента в блюде', validators=[django.core.validators.MinValueValidator(1, message='Мин. количество ингредиентов 1')], verbose_name='Количество'),
        ),
    ]
